# Generated by Django 5.1.5 on 2025-05-03 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
